# Generated by Django 3.2.23 on 2026-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_albumcomment'),
        ('users', '0002_auto_20251224_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites_tracks',
            field=models.ManyToManyField(blank=True, related_name='fav_by_users', to='artists.Track'),
        ),
    ]
