# Generated by Django 3.2.23 on 2026-01-28 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20260128_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genres', '0002_auto_20260128_2038'),
        ('users', '0003_alter_userprofile_favorites_tracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户页', 'verbose_name_plural': '用户页'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='简述'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorites_artists',
            field=models.ManyToManyField(blank=True, related_name='fav_by_users', to='artists.Artist', verbose_name='收藏的艺术家'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorites_tracks',
            field=models.ManyToManyField(blank=True, related_name='fav_by_users', to='artists.Track', verbose_name='收藏的音乐'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='instagram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='music_genres',
            field=models.ManyToManyField(blank=True, related_name='users_with_genre', to='genres.Genre', verbose_name='喜欢曲风'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='soundcloud',
            field=models.URLField(blank=True, verbose_name='soundcloud'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='twitter'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
