# Generated by Django 3.2.23 on 2026-02-04 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20260128_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20260128_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites_tracks',
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='歌单名称')),
                ('description', models.TextField(blank=True, verbose_name='歌单简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='users/playlists/', verbose_name='歌单封面')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracks', models.ManyToManyField(blank=True, related_name='in_playlists', to='artists.Track', verbose_name='歌曲')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '歌单',
                'verbose_name_plural': '歌单',
                'ordering': ['-created_at'],
            },
        ),
    ]
