# Generated by Django 3.2.23 on 2026-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20260128_2038'),
        ('events', '0003_auto_20260127_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='events', to='genres.Genre', verbose_name='曲风'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='是否在轮播图显示'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=200, verbose_name='组织方'),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='events/posters/', verbose_name='海报'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='票价'),
        ),
        migrations.AlterField(
            model_name='event',
            name='purchase_info',
            field=models.TextField(blank=True, verbose_name='购票方式说明'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_link',
            field=models.URLField(blank=True, verbose_name='购票链接'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='活动标题'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=200, verbose_name='地点'),
        ),
    ]
