# Generated by Django 3.2.23 on 2025-12-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/audio/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tracks/covers/')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('plays', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tracks', to='artists.artist')),
                ('genre_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='genres.genre')),
            ],
        ),
    ]
