# Generated by Django 3.2.23 on 2026-01-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_recommendationlog_track'),
        ('users', '0002_auto_20251224_1747'),
        ('core', '0002_auto_20260125_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Track',
        ),
    ]
