# Generated by Django 3.2.23 on 2025-12-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('community', '0003_auto_20251208_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='可选：将帖子与某个曲风绑定，方便在曲风详情页显示相关讨论。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='genres.genre'),
        ),
    ]
