# Generated by Django 3.2.23 on 2026-01-28 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': '曲风', 'verbose_name_plural': '曲风'},
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='曲风名'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subgenres', to='genres.genre', verbose_name='隶属'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='sample_audio',
            field=models.FileField(blank=True, null=True, upload_to='genres/samples/', verbose_name='音频文件'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='标签'),
        ),
    ]
