# Generated by Django 3.2.23 on 2025-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artist_tracks_by_genre', related_query_name='artist_track', to='genres.Genre'),
        ),
    ]
