# Generated by Django 3.2.23 on 2025-12-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_track_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='artists.Artist'),
        ),
    ]
