# Generated by Django 3.2.23 on 2026-01-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20251207_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='updated_at',
        ),
    ]
