# Generated by Django 3.2.23 on 2026-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20260120_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='专辑名')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL 标识')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='albums/covers/', verbose_name='专辑封面')),
                ('description', models.TextField(blank=True, verbose_name='专辑简介')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artists', models.ManyToManyField(related_name='albums', to='artists.Artist', verbose_name='制作人 / 艺术家')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
