# Generated by Django 3.2.23 on 2026-01-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0005_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-plays'], 'verbose_name': '歌曲', 'verbose_name_plural': '歌曲'},
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_tracks_by_genre', to='artists.album', verbose_name='所属专辑'),
        ),
        migrations.AddField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/covers/', verbose_name='歌曲封面'),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='时长（秒）'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/', verbose_name='音频文件'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artist_tracks_by_genre', related_query_name='artist_track', to='genres.Genre', verbose_name='曲风'),
        ),
        migrations.AlterField(
            model_name='track',
            name='plays',
            field=models.PositiveIntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='歌曲名'),
        ),
    ]
