# Generated by Django 3.2.23 on 2026-01-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0006_auto_20260122_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='artists.album', verbose_name='所属专辑'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artist_tracks', related_query_name='artist_track', to='genres.Genre', verbose_name='曲风'),
        ),
    ]
