# Generated by Django 3.2.23 on 2026-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_auto_20260128_2038'),
        ('artists', '0008_albumcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': '艺术家', 'verbose_name_plural': '艺术家'},
        ),
        migrations.AddField(
            model_name='track',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否为热门歌曲'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='artists/avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='genres.Genre', verbose_name='曲风'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='姓名'),
        ),
    ]
