# Generated by Django 3.2.23 on 2026-02-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20260128_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='likes',
        ),
    ]
