# Generated by Django 3.2.23 on 2026-01-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_albumcomment'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationlog',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.track'),
        ),
    ]
